### ISSUE TITLE
Broken path from 'Treasury' page

### ISSUE THREAD

**Issue by l33d4n** [terra-money/docs#11]
I found broken path from the 'Treasury' page, under the 'Parameters' section:

https://docs.terra.money/terracli/treasury.html#parameters

![image](https://user-images.githubusercontent.com/8020386/89729655-58d58c00-da6a-11ea-9999-4d59febeeca3.png)

**Comment by l33d4n** [comment]
@ouiliame, can you check it out?

**Comment by orthory** [comment]
@Daniel-Leedan PR is made, thanks for the heads up! In the meanwhile, you can access the page at https://docs.terra.money/dev/spec-treasury.html#parameters. The link also should work after it's deployed.
