### ISSUE TITLE
Tax on MsgSwapSend

### ISSUE THREAD

**Issue by ShadoySV** [terra-money/docs#196]
The [doc](https://docs.terra.money/Reference/Terra-core/Module-specifications/spec-market.html#msgswapsend) says:

> A MsgSendSwap first performs a swap of OfferCoin into AskDenom and then sends the resulting coins to ToAddress. Tax is charged normally, as if the sender were issuing a MsgSend with the resulting coins of the swap.

but actually tax is charged on offer coins, for example [here](https://github.com/terra-money/core/blob/d6037b9a12c8bf6b09fe861c8ad93456aac5eebb/custom/auth/client/utils/feeutils.go#L235) and [here](https://github.com/terra-money/core/blob/d6037b9a12c8bf6b09fe861c8ad93456aac5eebb/custom/auth/ante/tax.go#L124)

Please correct me if I am wrong.

**Comment by evanorti** [comment]
Thanks for bringing up this issue! I notice there are a few errors in this section. I will get these rectified.

**Comment by evanorti** [comment]
This section has been updated. Thanks for your feedback.
