### ISSUE TITLE
Terra station download links broken

### ISSUE THREAD

**Issue by tenjaa** [terra-money/docs#209]
Hi,
it seems that the download links at https://docs.terra.money/Tutorials/Get-started/Terra-Station-desktop.html#install-terra-station are broken.
Unfortuantely I cannot see any releases at all when looking manually at https://github.com/terra-money/station/releases/

**Comment by stevenTerra** [comment]
Thanks for letting us know. We updated the links in [PR #211](https://github.com/terra-money/docs/pull/211).
