### ISSUE TITLE
Malformed .json in bombay addressbook link. 

### ISSUE THREAD

**Issue by rtviii** [terra-money/docs#227]
In [this](https://docs.terra.money/How-to/Run-a-full-Terra-node/Join-public-network.html#pick-a-network) section of the docs the [link](https://network.terra.dev/testnet/addrbook.json) to the `bombay-12` testnet address-book (https://network.terra.dev/testnet/addrbook.json) points to a file that cuts off. 

Not sure if changing the link to the github blob is a good idea, otherwise would've done a pull with change.

**Comment by evanorti** [comment]
@octalmage

**Comment by Jared-TFL** [comment]
removed confusing section.
