### ISSUE TITLE
Unable to run scaffolded frontend application because the file `../refs.terrain.json` can't be resolved 

### ISSUE THREAD

**Issue by WojciechKo** [terra-money/docs#243]
Relates to: https://docs.terra.money/docs/develop/dapp/quick-start/using-terrain-testnet.html

When I follow the instructions and run `npm start` from the step "6. Front-end scaffolding", I'm getting an error:

```
Failed to compile.

./src/contract/address.js
Module not found: Can't resolve '../refs.terrain.json' in '/home/user/dev/my-terra-dapp/frontend/src/contract'
```

**Comment by evanorti** [comment]
Thanks for bringing these up! Let me resolve this and get back to you.

**Comment by lopezj19** [comment]
> Relates to: https://docs.terra.money/docs/develop/dapp/quick-start/using-terrain-testnet.html
> 
> When I follow the instructions and run `npm start` from the step "6. Front-end scaffolding", I'm getting an error:
> 
> ```
> Failed to compile.
> 
> ./src/contract/address.js
> Module not found: Can't resolve '../refs.terrain.json' in '/home/user/dev/my-terra-dapp/frontend/src/contract'
> ```

Hello @WojciechKo  , A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> Relates to: https://docs.terra.money/docs/develop/dapp/quick-start/using-terrain-testnet.html
> 
> When I follow the instructions and run `npm start` from the step "6. Front-end scaffolding", I'm getting an error:
> 
> ```
> Failed to compile.
> 
> ./src/contract/address.js
> Module not found: Can't resolve '../refs.terrain.json' in '/home/user/dev/my-terra-dapp/frontend/src/contract'
> ```

Hello, A support ticket has been opened for you with Support ticket number TMB899. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by evanorti** [comment]
This issue has been resolved. Thanks!
