### ISSUE TITLE
Terra Luna gone from Terra Station

### ISSUE THREAD

**Issue by Gijanekris** [terra-money/docs#245]
I received a message to update my Terra Station.  I could not proceed with out it.  When it was done updating all of my Terra Luna was gone.  I had about 8 Terra Luna staked

**Comment by evanorti** [comment]
Hello!

Please make sure you are logged into your wallet, and check the "Stake" section of Terra Station. It will show your staked Luna. 

If you are still having trouble, please try viewing your wallet address in finder:

https://finder.terra.money/

Input your wallet address and it will show you an overview of what tokens you have and who you are staked with.

Remember, NEVER give your seed phrase to anyone ever, not even support personnel.

**Comment by Gijanekris** [comment]
I see it now thanks.  The ICON for my T

**Comment by Gijanekris** [comment]
The Icon for my Terra Station is no longer there.  Its just a blank space
with gear in the middle.

**Comment by evanorti** [comment]
@Gijanekris you are probably seeing the shortcut to the old version of station installed. The updated station app you downloaded should be located in your Applications folder for Mac or in the programs menu for windows. Try seeing if the new station is accessible, and drag that to wherever you want it to be.  Then delete the old station file (the one with the gear).
