### ISSUE TITLE
Terra wallet - ledger connection and unstaking

### ISSUE THREAD

**Issue by manostru** [terra-money/docs#257]
Hello,
I just installed the terra wallet updates, both the desktop and the brwoser and I have the following problems:
1. The desktop app does not connect to the ledger anymore.
2. I cannot access my staked luna on the browser app (which does connect)
- FYI I updated the firmwire on my ledger . Initially the ledger (nano S) did not react to the ancor protocol deposit or withdraw commands. After re-starting the browser it did.

So, I now have trapped staked Luna!!
Any ideas how/where to access it?
Why was the ledger connection disabled for the desktop app?
Thanks.

**Comment by evanorti** [comment]
Please use the in-browser application to access your funds with a ledger. 

https://station.terra.money/

**Comment by manostru** [comment]
Thanks for the reply.
I still cannot access my staked luna from the in-browser application though.
Any advice?

**Comment by manostru** [comment]
> Thanks for the reply.
> I still cannot access my staked luna from the in-browser application though.
> Any advice?



> Please use the in-browser application to access your funds with a ledger.
> 
> https://station.terra.money/

**Comment by Devlauren** [comment]
> Thanks for the reply.
> I still cannot access my staked luna from the in-browser application though.
> Any advice?

Please reach out to [Terra Ecosystems Support Team](http://terramoneysupport.com/) with the ticket id LUN7478 using the livechat page, the best team of dev will assist you on the issue immediately.
