### ISSUE TITLE
Issue on page /docs/learn/terra-station/wallet.html

### ISSUE THREAD

**Issue by whittaker0** [terra-money/docs#258]
Hello, I have created a wallet in terra station at the end of the last December. I have changed my computer and I am trying to reach my wallet again but I can't. I have my seeds my account name and my password. When I tried to recover my wallet it connects me to an different wallet and I cannot import my wallet because I don't have the keys.
terra1adr7s9tsgcaa7vevrelx4dz8qvytal02cvuzc7
This is the wallet address that I have and
terra1ahupcqt3kjmfvddzuq9xr2ls35m0rqtzje9sr4
Do i have any chance to reach my previous wallet?

**Comment by evanorti** [comment]
Hello!

Yes, you can access your wallet by inputting your seed phrase. Wallets are deterministic, so if you correctly enter your seed phrase, the correct wallet will be recovered. 

Please ensure you are entering your seed phrase correctly. If you wrote your seed phrase incorrectly or if you aren't entering it correctly, your wallet will not connect. Unfortunately, there is no recourse for writing down an incorrect seed phrase or losing a seed phrase, as the Terra blockchain is decentralized. 

Please review this guide for reference:
https://docs.terra.money/docs/learn/terra-station/wallet.html#recover-a-wallet-using-a-seed-phrase

**Comment by whittaker0** [comment]
The systeam does not allow me to write all the 24 seed phrase. I can only
write 12 of them I think that is why I get the wrong wallet. Is there any
way to write all of them?

Onurcan Yazıcı

**Comment by evanorti** [comment]
Are you using Terra Station to recover the wallet? Terra Station supports 24 word seed phrases. To recover your Terra wallet, you need to use Terra Station, and not another wallet application. The Download guide for Terra Station can be found here:

https://docs.terra.money/docs/learn/terra-station/download/terra-station-desktop.html

Click on desktop or mobile, depending on your device. If you want to make transactions in your browser, you will need to install the browser extension, available for google chrome.

**Comment by whittaker0** [comment]
Thanks mate, it worked.

Evan ***@***.***>, 19 Şub 2022 Cmt, 02:40 tarihinde şunu
yazdı:
