### ISSUE TITLE
failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker

### ISSUE THREAD

**Issue by Anastasia21O** [terra-money/docs#261]
Error:
failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): store wasm contract failed: invalid request

The repository from which we compiled the contract:
https://github.com/CosmWasm/cw-nfts

The contract we want to generate (*.wasm):
[cw-nfts](https://github.com/CosmWasm/cw-nfts)/[contracts](https://github.com/CosmWasm/cw-nfts/tree/main/contracts)/cw721-metadata-onchain/

Different ones were used branches and tags for implementation *.wasm files, but the error remained the same.
Commands used:
1)	sudo docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer:0.12.4

2)	rustc --version
cargo --version
rustup target list --installed
# if wasm32 is not listed above, run this
rustup target add wasm32-unknown-unknown14:38
 
# this will produce a wasm build in ./target/wasm32-unknown-unknown/release/YOUR_NAME_HERE.wasm
cargo wasm

# this runs unit tests with helpful backtraces
RUST_BACKTRACE=1 cargo unit-test

# auto-generate json schema
cargo schema14:38

RUSTFLAGS='-C link-arg=-s' cargo wasm14:38
НВ
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.11.4
3)	RUSTFLAGS='-C link-arg=-s' cargo wasm
cp ../../target/wasm32-unknown-unknown/release/cw721_base.wasm .
ls -l cw721_base.wasm
sha256sum cw721_base.wasm

**Comment by evanorti** [comment]
@octalmage please review.

**Comment by octalmage** [comment]
Hey @Anastasia21O, this error usually means you're using CosmWasm 1.0 while Terra only supports 0.16. You can find the correct cw721 contracts here: 

https://github.com/CosmWasm/cw-plus/tree/0.9.x/contracts
