### ISSUE TITLE
Please use the in-browser application to access your funds with a ledger.

### ISSUE THREAD

**Issue by manostru** [terra-money/docs#264]
Please use the in-browser application to access your funds with a ledger. 

https://station.terra.money/

_Originally posted by @evanorti in https://github.com/terra-money/docs/issues/257#issuecomment-1043685595_

**Comment by manostru** [comment]
Sorry, but this is not completely resolved.
Accesing my wallet through my ledger was possible using the in-browser app.
BUT:
I still cannot access my STAKED luna from the in-browser application though.
Where can I see all my staked LUNA? There is no menu in the in-browser app for that and there is no option to connect my ledger in the desktop app.
Any advice?

Thanks.

**Comment by evanorti** [comment]
1. Please navigate to https://station.terra.money/ in your browser. This is separate from the extension. 
2. Click "Connect" located in the upper right corner. Connect your ledger. 
3. Click "Stake" located on the left menu.

This page will allow you to access your delegations.

**Comment by evanorti** [comment]
@manostru are you able to access your delegations?

**Comment by manostru** [comment]
Hello,
Thanks for the response.
I knew I was doing something wrong.
I was just viewing the wallet extension (chrome-extension://.....)
And not the full terra wallet.

So, YES, I can see everything now.
Thanks a lot.
Problem solved.
