### ISSUE TITLE
Issue on page /docs/ecosystem/integrations.html

### ISSUE THREAD

**Issue by ronlobo** [terra-money/docs#272]
You have an application listed called `PaywithTerra - An API gateway enabling merchants to accept Terra stable coins`.

Upon further research, I came to the conclusion that this is fishy.

Why?

- no website whois
- listed as PaywithTerra LLC, Switzerland, Canton of Geneva (see terms), no LLC can for that name be found here: https://www.ge.ch/recherche-entreprises-dans-registre-du-commerce-geneve
- The creator is from Minsk, Belarus: https://agora.terra.money/u/task-euler/summary

Please do some research before blindly listing such things.

**Comment by evanorti** [comment]
The community voted to fund paywithterra:

https://station.terra.money/proposal/51

If you suspect them of anything, I encourage you to bring it up with the community. 

If you have suggestions for the community ecosystem page, please submit a pull request. 

Thank you.
