### ISSUE TITLE
Issue on page /docs/learn/terra-station/README.html

### ISSUE THREAD

**Issue by norahenes** [terra-money/docs#273]
Entered memo for UST-transaction from Binance to Terra Station where no memo is needed.
Deposit did not arrive. 
Asking to retrieve the transaction or direct it to wallet.

**Comment by simcheolhwan** [comment]
Find the tx link from Binance please.

**Comment by norahenes** [comment]
I have it. Self Service Recovery from Binance did not approve the information given to retrieve transaction.

**Comment by norahenes** [comment]
71497CC407A549CC92B614AF29A1DBB941644CA616269EDA3C1497ECA349F3F2

**Comment by norahenes** [comment]
thank you so much for you fast reply

**Comment by simcheolhwan** [comment]
Would you provide as a link please?

**Comment by norahenes** [comment]
https://finder.terra.money/columbus-4/tx/71497CC407A549CC92B614AF29A1DBB941644CA616269EDA3C1497ECA349F3F2

**Comment by simcheolhwan** [comment]
Tx says that 1091 UST is sent to the `terra1395zz0p6mru84k0c9lxezfuxm547ftpfgrng7z`.
And `terra1395zz0p6mru84k0c9lxezfuxm547ftpfgrng7z` has 1091 UST. 
https://finder.terra.money/columbus-5/address/terra1395zz0p6mru84k0c9lxezfuxm547ftpfgrng7z
Nothing is wrong.

**Comment by norahenes** [comment]
oh fantastic! I checked again and found the transaction. Thank you lots for your help!
