### ISSUE TITLE
Issue on page /docs/develop/module-specifications/spec-market.html

### ISSUE THREAD

**Issue by Aureliano90** [terra-money/docs#284]
In section [Market Making Algorithm](https://docs.terra.money/docs/develop/module-specifications/spec-market.html#market-making-algorithm), the Constant Product is given by
```
CP = Pool_{Terra} * Pool_{Luna} * (Price_{Luna} / Price_{SDR}),
```
where
```
Pool_{Terra} is the number of virtual SDR. Pool_{Luna} is the number of virtual Luna.
```
Contradicting information is given in section [Virtual Liquidity Pools](https://docs.terra.money/docs/develop/module-specifications/spec-market.html#virtual-liquidity-pools), where
```
CP = (Pool_{Base})^2,
and Pool_{Luna} = (Pool_{Base})^2 / Pool_{Terra}.
```
The correct equation for `Pool_{Luna}` should be
```
Pool_{Luna} = (Pool_{Base})^2 / Pool_{Terra} / (Price_{Luna} / Price_{SDR}).
```

**Comment by evanorti** [comment]
@Aureliano90 Thanks for commenting!

Yes, the current wording and display of this equation is somewhat misleading, as the virtual pool of Luna is actually always denominated in SDR, and derived from the Terra pool size, as the Terra pool delta is the only variable that is actually tracked. 

I think the first equation you showed is trying to illustrate that Terra is using a uniswap-style pool, but the "Luna pool" is actually the price of a Luna pool in SDR, and not a fixed volume of Luna. 

The actual equations are here: 

https://github.com/terra-money/core/blob/main/x/market/keeper/swap.go#L100

``` go
cp := basePool.Mul(basePool)
	terraPoolDelta := k.GetTerraPoolDelta(ctx)
	terraPool := basePool.Add(terraPoolDelta)
	lunaPool := cp.Quo(terraPool)
```

This module spec is actually being re-written to reflect the code more accurately, so keep an eye out and it will be changed this week. 

Again, thank you for your comment!
