### ISSUE TITLE
Unclear: Market Spec Luna fiat value

### ISSUE THREAD

**Issue by Ra0R** [terra-money/docs#296]
`With Constant Product, a value, CP, is set to the size of the Terra pool multiplied by a set fiat value of Luna, and ensure our market-maker maintains it as invariant during any swaps by adjusting the spread.`

I was wondering in which fiat currency Luna is measured? It is not directly specified.

**Comment by evanorti** [comment]
Thanks for your question!

Both the Terra and Luna virtual pool amounts are measured in µSDR. The pool values are not actually tracked, only the TerraPoolDelta (the amount changed from the basepool param in µSDR) is tracked. Pool sizes can be derived with the following equations:

TerraPoolSize = Basepool + TerraPoolDelta

LunaPoolSize = ConstantProduct/ (Basepool + TerraPoolDelta)
Terra 

ConstantProduct = Basepool^2

All units are in µSDR for simplicity. 

 A new module-spec for the market module will be released this week, clarifying this and many other points.
