### ISSUE TITLE
Issue on page /docs/learn/terra-station/wallet.html

### ISSUE THREAD

**Issue by blair4444** [terra-money/docs#299]
I created a wallet using the Terra Station chrome extension with my ledger nanoS. I deposited some UST into it. I inadvertently deleted the wallet and tried to recover it with the ledger. Unfortunately, it generated an entirely different address that has no money in it. I can clearly see my original wallet address n the blockchain, but cannot access it with my Terra Station/Ledger. Can anyone help me get back to my wallet?

**Comment by emidev98** [comment]
Hello @blair4444, we or the community will try to help, join our Discord https://discord.gg/7QVbggYZ and lets take a closer look on your case. Thanks :100:

**Comment by blair4444** [comment]
Can you resend the discord invitation please? This one is invalid.

**Comment by emidev98** [comment]
You can use the one from the [official website](https://www.terra.money/), top right, 4th logo
![image](https://user-images.githubusercontent.com/49301655/161780687-0efa68df-2a0b-4ebf-a049-8d99716954f0.png)

**Comment by blair4444** [comment]
<img width="499" alt="Screen Shot 2022-04-05 at 12 37 58 PM" src="https://user-images.githubusercontent.com/99218520/161835977-f3ec6ba1-f147-4e0b-88e3-5cbb426d1634.png">

**Comment by blair4444** [comment]
Your discord group requires an invitation to join. Can you please send me an invitation this isn't expired? Thank you

**Comment by blair4444** [comment]
My mistake. I am in the discord server now.
