### ISSUE TITLE
Dead link in oracle docs

### ISSUE THREAD

**Issue by etienne-napoleone** [terra-money/docs#3]
dead link to the voting procedure (https://docs.terra.money/validator/spec-oracle.html#voting-procedure) on page https://github.com/terra-project/docs/blob/master/src/validator/oracle.md

**Comment by etienne-napoleone** [comment]
Also here https://docs.terra.money/terracli/oracle.html#submit-an-exchange-rate-vote in
> section of the Validator Handbook, and the Oracle Module Specification.

**Comment by dokwon** [comment]
Is there a sanity checker we could run in the CI to make sure all the links are alive?

**Comment by etienne-napoleone** [comment]
Yes! there's not CI yet tho, I think @ouiliame deploys using this [script](https://github.com/terra-project/docs/blob/master/deploy.sh). I'll add a github workflow to take care of publishing on gh pages and do 404 checks

**Comment by ouiliame** [comment]
CI is set up by @YunSuk-Yeo

**Comment by etienne-napoleone** [comment]
I'll take care of it!

**Comment by etienne-napoleone** [comment]
will be integrated in CI when #6 is merged

**Comment by etienne-napoleone** [comment]
https://github.com/terra-project/docs/actions?query=workflow%3A%22Test+links%22
this workflow tests for dead links on docs.terra.money and is triggered after a new page deployment

```
![Test links](https://github.com/terra-project/docs/workflows/Test%20links/badge.svg?branch=master)
```

badge link (![Test links](https://github.com/terra-project/docs/workflows/Test%20links/badge.svg?branch=master))
