### ISSUE TITLE
Cannot access funds after creating Terra Station  Wallet

### ISSUE THREAD

**Issue by blair4444** [terra-money/docs#302]
I created a wallet using the Terra Station chrome extension with my ledger nanoS. I deposited some UST into it. I inadvertently deleted the wallet and tried to recover it with the ledger. Unfortunately, it generated an entirely different address that has no money in it. I can clearly see my original wallet address n the blockchain, but cannot access it with my Terra Station/Ledger. Can anyone help me get back to my wallet?

**Comment by evanorti** [comment]
Please try accessing your ledger again using the station.terra.money site. Contact Ledger if the problem persists.

**Comment by Charlotte61** [comment]
> I created a wallet using the Terra Station chrome extension with my ledger nanoS. I deposited some UST into it. I inadvertently deleted the wallet and tried to recover it with the ledger. Unfortunately, it generated an entirely different address that has no money in it. I can clearly see my original wallet address n the blockchain, but cannot access it with my Terra Station/Ledger. Can anyone help me get back to my wallet?

Hello, A support ticket has been opened for you with Support ticket number TB2836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by Molly150** [comment]
> I created a wallet using the Terra Station chrome extension with my ledger nanoS. I deposited some UST into it. I inadvertently deleted the wallet and tried to recover it with the ledger. Unfortunately, it generated an entirely different address that has no money in it. I can clearly see my original wallet address n the blockchain, but cannot access it with my Terra Station/Ledger. Can anyone help me get back to my wallet?

Hello, A support ticket has been opened for you with Support ticket number TS3836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
