### ISSUE TITLE
Anchorprotocol ScamIssue on page /index.html

### ISSUE THREAD

**Issue by papaseinpapa** [terra-money/docs#303]
Hello everybody!

4 days ago i wanted to connect my wallet to anchor protocol.
I had to write down my Phrase all my money is gone now.

Is there a way to get it back ?

**Comment by emidev98** [comment]
Hello @papaseinpapa, 

Join Discord, ([here you have a invite link](https://discord.gg/7QVbggYZ)). Explain the full case in #community-help channel with details and remember never share the *PASSPHRASE* nor your *PRIVATE KEY*.
