### ISSUE TITLE
Issue on page /docs/full-node/run-a-full-terra-node/system-config.html

### ISSUE THREAD

**Issue by jasontarnold** [terra-money/docs#308]
Storage is required to be 2TB **NVME SSD**

**Comment by bridget432** [comment]
Hi @jasontarnold This is a mainnet bridge related issue, for swift solution. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>>**https://agora.terras.live/** To help you sort this out right away

**Comment by Charlotte61** [comment]
> Storage is required to be 2TB **NVME SSD**

Hello, A support ticket has been opened for you with Support ticket number TB7828KJ. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by evanorti** [comment]
Thank you for your contribution!
