### ISSUE TITLE
Typo on REST API

### ISSUE THREAD

**Issue by fenghaojiang** [terra-money/docs#316]
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/28303956/163786318-f2a1dfc0-03d9-4562-ab69-da8bf495f3a2.png">

I think it should be "validator". Plz check and modify it.
Here is your docs URL: https://lcd.terra.dev/swagger/#/Query/AggregateVote

**Comment by emidev98** [comment]
Hello @fenghaojiang,
Based on REST [standard](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#what-is-rest) should be plural:
`Adopt a consistent naming convention in URIs. In general, it helps to use plural nouns for URIs that reference collections. It's a good practice to organize URIs for collections and items into a hierarchy. For example, /customers is the path to the customers collection, and /customers/5 is the path to the customer with ID equal to 5. This approach helps to keep the web API intuitive. Also, many web API frameworks can route requests based on parameterized URI paths, so you could define a route for the path /customers/{id}.`

**Comment by fenghaojiang** [comment]
I do not quite understand you. Do you mean you designed the API name on purpose?

> Hello @fenghaojiang, Based on REST [standard](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#what-is-rest) should be plural: `Adopt a consistent naming convention in URIs. In general, it helps to use plural nouns for URIs that reference collections. It's a good practice to organize URIs for collections and items into a hierarchy. For example, /customers is the path to the customers collection, and /customers/5 is the path to the customer with ID equal to 5. This approach helps to keep the web API intuitive. Also, many web API frameworks can route requests based on parameterized URI paths, so you could define a route for the path /customers/{id}.`

**Comment by emidev98** [comment]
My bad, I double checked and there is a typo **valdiators** which should be **validators**.

Thanks for the info! I will check with the team

**Comment by fenghaojiang** [comment]
> My bad, I double checked and there is a typo **valdiators** which should be **validators**.
> 
> Thanks for the info! I will check with the team

xD, I will close this issue
