### ISSUE TITLE
Where are the private keys & Mnemonic keys are stored?

### ISSUE THREAD

**Issue by KorayBarkin** [terra-money/docs#319]
Hello, whenever I create a account with public & private key pairs I would like to know where it is stored. I can't even view my private key. terrad keys show "username" or terrad keys list doesn't show mnemonic and priv keys. There is a file named node_key.json under config file but I don't think that is the private key for the "username".

**Comment by KorayBarkin** [comment]
As far as I understand, Mnemonic keys are generated when the account is created and user needs to store it. Neither terra nor local system doesn't store mnemonic keys. However, private keys needs to be held in somewhere in my local server but where? When I create a wallet with:
  const mk = new MnemonicKey();
  const wallet = terra.wallet(mk);

I want to store the wallet's private key where the others are stored. Otherwise, I just create a wallet and release it to the air.

**Comment by ericHgorski** [comment]
Hi, please use the [terra discord](https://discord.com/invite/terra-money) for general technical questions.

**Comment by steward833** [comment]
> Hello, whenever I create a account with public & private key pairs I would like to know where it is stored. I can't even view my private key. terrad keys show "username" or terrad keys list doesn't show mnemonic and priv keys. There is a file named node_key.json under config file but I don't think that is the private key for the "username".

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
