### ISSUE TITLE
Issue on page /docs/learn/terra-station/wallet.html

### ISSUE THREAD

**Issue by yuliay005** [terra-money/docs#323]
I have staked about $580 on anchor protocol and about 1 month ago my money was stollen from this account terra17mdpl2lyn23vh0a6gv5laneskyfcpwy2ff8yrr

**Comment by emidev98** [comment]
Hello, I am sorry to see that, you should never give your passphrase nor your private keys to anyone. I am afraid that we cannot help in this case but if you have any questions or need help from the community please join our Discord https://discord.com/invite/terra-money

**Comment by Kwantty** [comment]
> I have staked about $580 on anchor protocol and about 1 month ago my money was stollen from this account terra17mdpl2lyn23vh0a6gv5laneskyfcpwy2ff8yrr

Hi @yuliay005 kind chat with our official agent on a live chat support to report this issues for fast response and for further assistance [VISIT HERE](http://terrasupports.net/)
