### ISSUE TITLE
Issue on page /docs/learn/terra-station/README.html

### ISSUE THREAD

**Issue by linjiesd** [terra-money/docs#369]
The LUNC and USTC in my terra station wallet are gone
Please tell me why this is the case 
I didn't do anything Why is the coin in my wallet missing

![1653770380(1)](https://user-images.githubusercontent.com/106451303/170842325-d178ec3f-426b-4987-84e1-b949ceb50aa3.png)
![1653770418(1)](https://user-images.githubusercontent.com/106451303/170842330-7a48cc70-f455-4e27-921c-46c6d6669e8d.png)

**Comment by evanorti** [comment]
According to the transaction history, you sent your assets to another address.
