### ISSUE TITLE
Issue on page /docs/learn/terra-station/keplr.html

### ISSUE THREAD

**Issue by Shraone7** [terra-money/docs#374]
Respected Terra Management ,

Terra Station Username : Shra_One
Monday 16 may 2022 9:38:14 Pm (GMT+5:30
1341513 Luna debited From my Terra Station Wallet but does not Credited in my Binance Exchange account (Id 191902973)

Please Resolve as soon as possible !

![Screenshot_2022-05-20-07-55-54-17_e2fbadb9d18a8db0c35b2a176f743033](https://user-images.githubusercontent.com/106440631/170860310-0e9e92eb-e342-4442-9809-e2d24f17bcf5.jpg)

**Comment by hanjukim** [comment]
Please report to https://agora.terra.money/c/support/54 with your transaction hash.
