### ISSUE TITLE
Notification error sending LUNC from chrome extension to Kucoin

### ISSUE THREAD

**Issue by pdogg78** [terra-money/docs#385]
Dear sir/madam,
I get the following failure code when I try to send LUNC to Kucoin via the downloaded chrome extension. The error it is about fees I guess, but I can not change it.
Can you help me with a solution so that I can send my LUNC ?
My adress: terra1ev2jg32mw70vfufpgyhuftdwlqtpyjggmdkjak

I hope you can help me out here.
thanks.
Have a good day. 
Pdogg78

Error message:
insufficient fees; got: "15885uluna", required: "20121uaud,20121ucad,14826uchf,103782ucny,95310udkk,13238ueur,11649ugbp,123903uhkd,230862000uidr,1152192uinr,1733583ujpy,17978643ukrw,599924uluna,45385669umnt,63540umyr,132375unok,804840uphp,11113usdr,132375usek,21180usgd,489258uthb,423600utwd,15885uusd" = "20121uaud,20121ucad,14826uchf,103782ucny,95310udkk,13238ueur,11649ugbp,123903uhkd,230862000uidr,1152192uinr,1733583ujpy,17978643ukrw,599924uluna,45385669umnt,63540umyr,132375unok,804840uphp,11113usdr,132375usek,21180usgd,489258uthb,423600utwd,15885uusd"(gas) +""(stability): insufficient fee

![error](https://user-images.githubusercontent.com/106622775/171262320-abfa408a-56db-424f-90d3-41e488654113.PNG)

Error message:
insufficient fees; got: "15885uluna", required: "20121uaud,20121ucad,14826uchf,103782ucny,95310udkk,13238ueur,11649ugbp,123903uhkd,230862000uidr,1152192uinr,1733583ujpy,17978643ukrw,599924uluna,45385669umnt,63540umyr,132375unok,804840uphp,11113usdr,132375usek,21180usgd,489258uthb,423600utwd,15885uusd" = "20121uaud,20121ucad,14826uchf,103782ucny,95310udkk,13238ueur,11649ugbp,123903uhkd,230862000uidr,1152192uinr,1733583ujpy,17978643ukrw,599924uluna,45385669umnt,63540umyr,132375unok,804840uphp,11113usdr,132375usek,21180usgd,489258uthb,423600utwd,15885uusd"(gas) +""(stability): insufficient fee

**Comment by emidev98** [comment]
Hey, this is not the right place for this kind of requests. Can you check in [Terra Discord](https://terra.sc/discord)? Thanks.
