### ISSUE TITLE
Issue on page /docs/develop/terrain/using-terrain-localterra.html

### ISSUE THREAD

**Issue by kimberger** [terra-money/docs#389]
The project structure created when using `terrain new my-terra-dapp` does not match the documented structure. The subfolder created is `contracts/my-terra-dapp`.

Which means when you get to the deploy step: `terrain deploy counter --signer test1` you receive the following error:

```
➜  my-terra-dapp terrain deploy counter --signer test1
using pre-baked 'test1' wallet on localterra as signer
    Error: ENOENT: no such file or directory, chdir '/home/XXX/Code/my-terra-dapp' -> 'contracts/counter'
    Code: ENOENT
```

**Comment by evanorti** [comment]
@emidev98

**Comment by taitruong** [comment]
I figured that out as well and opened a bug in terrain repo: https://github.com/terra-money/terrain/issues/93
