### ISSUE TITLE
Issue on page /docs/learn/terra-station/README.html

### ISSUE THREAD

**Issue by 007ham** [terra-money/docs#392]
I have transferred terra luna from exchange to terra station and nothing has come to the terra station as off yet

**Comment by 007ham** [comment]
I would advise you to reach out to the receiving platform, and provide them the following TxHash: 65b2f5d8c176a67e28e084c80e42d6082a12813e6dc1d02e2daeba113b739769

**Comment by emidev98** [comment]
Hey, this space is dedicated to issues related the docs, could you check in Discord (https://discord.com/invite/terra-money) or Telegram (https://t.me/TerraLunaChat) community ? Thanks
