### ISSUE TITLE
Deploying contract: Wasm contract has unknown interface_version_* marker export

### ISSUE THREAD

**Issue by taitruong** [terra-money/docs#397]
Working my way through the docs for smart contract guide. Trying to deploy my-first-contract to localterra as described here: https://docs.terra.money/docs/develop/guides/smart-contracts/interact-with-smart-contract.html
Error:

> $ terrad tx wasm store artifacts/my_first_contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block
>
> Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interfaceversion* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): create wasm contract failed: invalid request

This error has also been filed in issue #261:
> Hey @Anastasia21O, this error usually means you're using CosmWasm 1.0 while Terra only supports 0.16. You can find the correct cw721 contracts here:
>
> https://github.com/CosmWasm/cw-plus/tree/0.9.x/contracts
>
> from docs.

Honestly I don't know what to do here. Since comment refers to cw-plus but I created project using cw-template and branch 0.16 using this command as described in docs: https://docs.terra.money/docs/develop/guides/smart-contracts/write-smart-contract.html
> $ cargo generate --git https://github.com/CosmWasm/cw-template.git --branch 0.16^C-name my-first-contract

**Comment by emidev98** [comment]
Hey @taitruong, the error you're seeing is because cosmwasm-std from your smart contract is incompatible with the on chain cosmwasm-vm ([more info here](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md#compatibility)). This can be because of many reasons deep inside the smart contract. 

You can try:
- using cosmwasm-std 1.0. 
- or try instantiating the code with [Terrain](https://github.com/terra-money/terrain).

If the previous options does not work please join [Terra Discord](https://terra.sc/discord) with the Developer role where you can get a in-detail help from the comunity or mods.

**Comment by taitruong** [comment]
> Hey @taitruong, the error you're seeing is because cosmwasm-std from your smart contract is incompatible with the on chain cosmwasm-vm ([more info here](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md#compatibility)). This can be because of many reasons deep inside the smart contract.
> 
> You can try:
> 
> * using cosmwasm-std 1.0.
> * or try instantiating the code with [Terrain](https://github.com/terra-money/terrain).
> 
> If the previous options does not work please join [Terra Discord](https://terra.sc/discord) with the Developer role where you can get a in-detail help from the comunity or mods.

Ok, I have created project with main branch (without --branch 0.16 option):
> $ cargo generate --git https://github.com/CosmWasm/cw-template.git --name my-1st-contract
Docs should be updated here: https://docs.terra.money/docs/develop/guides/smart-contracts/write-smart-contract.html

But when  deploying contract results to insufficient funds error:

> $ terrad tx wasm store artifacts/my_first_contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block
> 
> gas estimate: 959327
{"body":{"messages":[{"@type":"/cosmwasm.wasm.v1.MsgStoreCode","sender":"terra1dcegyrekltswvyy0xy69ydgxn9x8x32zdtapd8","wasm_byte_code":"...GLuUGAgA=","instantiate_permission":null}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uluna","amount":"100000"}],"gas_limit":"959327","payer":"","granter":""}},"signatures":[]}
> 
> confirm transaction before signing and broadcasting [y/N]: y
> code: 13
> codespace: sdk
> data: ""
> events: []
> gas_used: "3429"
> gas_wanted: "959327"
> height: "0"
> info: ""
> logs: []
> raw_log: 'insufficient fees; got: 100000uluna required: 143900uluna: insufficient fee'
> timestamp: ""
> tx: null
> txhash: EBC5357191501BBB6186C549B9563B2CFC03CF839E4EADF8A4144531E5FDFF09
