### ISSUE TITLE
Addressbook not found

### ISSUE THREAD

**Issue by Bohdan96** [terra-money/docs#407]
Good day.
Сannot start synchronization, as we do not have an addressbook for netwok mainet (used **columbus-5**), because on your documentation **link with addressbook https://network.terra.dev/addrbook.json dont work.**
Can you provide addressbook for the network columbus-5, please
![2022-07-12_09-46](https://user-images.githubusercontent.com/64528224/178428312-7f56e3cb-b49b-4f33-97d6-aecc06e5a67c.png)
?

**Comment by evanorti** [comment]
The Columbus-5 address book for Terra Classic can be found here:

https://classic-docs.terra.money/docs/full-node/run-a-full-terra-node/join-a-network.html#select-a-network

**Comment by Bohdan96** [comment]
But link at the page https://classic-docs.terra.money/docs/full-node/run-a-full-terra-node/join-a-network.html#select-a-network with addressbook https://network.terra.dev/addrbook.json dont work. Please, provide addressbook for the network columbus-5.
![2022-07-18_10-39](https://user-images.githubusercontent.com/64528224/179464924-50e017f0-1aaa-4e7c-ab1d-85ad8b2146df.png)
