### ISSUE TITLE
Should we get rid of inflation story on the docs?

### ISSUE THREAD

**Issue by pedro-explore** [terra-money/docs#42]
https://docs.terra.money/dev/spec-mint.html#the-minting-mechanism
https://docs.terra.money/terracli/mint.html
We have an inflation of 0% and annual provision of 0% right now. Inflation max/min of 0% as well.

I believe this is no longer used by Terra, should we get rid of these parts of docs? 
I think minting is just purely determined by demand for Luna and Terrastables.

**Comment by hanjukim** [comment]
Yes.
