### ISSUE TITLE
Issue on page /docs/develop/endpoints.html

### ISSUE THREAD

**Issue by PolinaShanti** [terra-money/docs#456]
Hey Terra Team!
My name is Polina, and I work for NOWNodes. We have been following your documentation about RPC and LCD endpoints.
Past some words about NOWNodes
We are a development service solution that provides full access to blockchain nodes, supports over 50 coins and tokens, and Terra Blockchain.

https://nownodes.io/

I'd like to know how I can add NOWNodes to the Private endpoints list in your doc?

Thank you!

**Comment by evanorti** [comment]
Hello Polina,

I took a look at your site, and it looks like you only support Terra Classic. These Docs are for the new Terra chain running on the Phoenix mainnet. If your company does end up supporting the Phoenix mainnet or testnet, you can put the Terra chain info on your website and then you can open a PR on the following page: 

https://docs.terra.money/develop/endpoints/#private-endpoints

Thanks!
