### ISSUE TITLE
Issue with  lunc wallet

### ISSUE THREAD

**Issue by Kaj1x** [terra-money/docs#476]
Hi  

Few weeks ago  i bought lunc and delegate it on terra station with Orion . Yesterday my mobile died and I cannot connect to wallet with another mobile only trough desktop  i still have phrase seed but i am experiencing that always when i trying recover wallet it instead of log me in, it create a new address how is this possible? I still see my wallet on desktop, even tried to scan from desktop but it didn't log me to my wallet.  Is this wallet lost or is any chance how to recover it.  I am not experienced and i never get out private key i just found it now  through tutorial how to do it.. But on desktop i can't do that. Not sure why. If is lost .. alright its happen, but if there is a option i would like to recover it.  Any help appreciate 

Regards,
Kaj1x

**Comment by evanorti** [comment]
For future reference, be aware that this repository is for the Terra network only, not Terra Classic.

If you are trying to view your Luna Classic, make sure you are on the Terra Classic network. You need to switch networks in your Station app:

https://docs.terra.money/learn/terra-station/networks
