### ISSUE TITLE
> **Describe the bug**

### ISSUE THREAD

**Issue by Aminkavoos** [terra-money/docs#496]
> **Describe the bug**
> Hi, our TRX (Tron) validator is still listed as inactive with APR of 0.0%. This is incorrect.
> 
> Super representatives and SR Partners receive rewards for TRX (Tron).
> Super Representatives: 1-27
> 
> SR Partners: 28-127 - https://tronscan.io/#/sr/representatives
> Our current ranking is 84 as can be seen by this link from the Tronscan website
> https://tronscan.io/#/address/TMAqheVWMaNm15UJTNgasEVpJ7YHYiZVZ8
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. iOS]
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. iPhone6]
>  - OS: [e.g. iOS8.1]
>  - Browser [e.g. stock browser, safari]
>  - Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
> 

Kindly file a support ticket for this concern below
https://forms.gle/KAqYDCGHb1UP4K8e7

_Originally posted by @Nanimustshine in https://github.com/trustwallet/assets/issues/22353#issuecomment-1260797000_

**Comment by Aminkavoos** [comment]
> > **Describe the bug**
> > Hi, our TRX (Tron) validator is still listed as inactive with APR of 0.0%. This is incorrect.
> > 
> > Super representatives and SR Partners receive rewards for TRX (Tron).
> > Super Representatives: 1-27
> > 
> > SR Partners: 28-127 - https://tronscan.io/#/sr/representatives
> > Our current ranking is 84 as can be seen by this link from the Tronscan website
> > https://tronscan.io/#/address/TMAqheVWMaNm15UJTNgasEVpJ7YHYiZVZ8
> > 
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > 
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > 
> > **Desktop (please complete the following information):**
> >  - OS: [e.g. iOS]
> >  - Browser [e.g. chrome, safari]
> >  - Version [e.g. 22]
> > 
> > **Smartphone (please complete the following information):**
> >  - Device: [e.g. iPhone6]
> >  - OS: [e.g. iOS8.1]
> >  - Browser [e.g. stock browser, safari]
> >  - Version [e.g. 22]
> > 
> > **Additional context**
> > Add any other context about the problem here.
> > 
> 
> Kindly file a support ticket for this concern below
> https://forms.gle/KAqYDCGHb1UP4K8e7
> 
> _Originally posted by @Nanimustshine in https://github.com/trustwallet/assets/issues/22353#issuecomment-1260797000_

**Comment by Rastaman231** [comment]
Bug

**Comment by independentcontractor66666gma** [comment]
Yea
