### ISSUE TITLE
Endpoint provider need to be updated

### ISSUE THREAD

**Issue by dev8723** [terra-money/docs#515]
provider listed [here](https://docs.terra.money/develop/endpoints/#private-endpoints) is outdated, i believe `quicknode` and `figment` are no longer supporting terra. we can leave `GetBlock` and add [setten](https://setten.io/).

**Comment by Stephen0531** [comment]
> provider listed [here](https://docs.terra.money/develop/endpoints/#private-endpoints) is outdated, i believe `quicknode` and `figment` are no longer supporting terra. we can leave `GetBlock` and add [setten](https://setten.io/).
Setten request withdraw

**Comment by evanorti** [comment]
Updating. Thank you!
