### ISSUE TITLE
Latest stable release is not on main branch, but on `release/vX.Y.Z`

### ISSUE THREAD

**Issue by taitruong** [terra-money/docs#574]
For finding latest release use this for example:

`git branch --all | grep release`

https://github.com/terra-money/docs/blob/89d45695af48c166ce0fbfc88bc40b5a863d8a7e/docs/develop/terrad/install-terrad.mdx#L50

**Comment by evanorti** [comment]
Hello! Thank you for bringing this up. The latest stable release is now on main and will track accurately in the future. 

Cheers!
