### ISSUE TITLE
tax reward denomination error

### ISSUE THREAD

**Issue by dokwon** [terra-money/docs#7]
https://docs.terra.money/luna.html#taxes describes the rewards that are paid out at the end of each block as denominated in TerraSDR. In fact, fees are paid out in all the Terra stablecoins

**Comment by ouiliame** [comment]
Fixed with 3cd0b7539bf3a33cc3e885b351f9c16700460e99

**Comment by ouiliame** [comment]
@dokwon FYI, feel free to edit any page directly -- added an "Edit with Github" link at the bottom of each page.
